name: avahi
version: 0
version-script: git describe --tags | cut -c 2-
summary: avahi-daemon 
description: |
  avahi service daemon

  Avahi is a free, LGPL implementation of DNS Service Discovery (DNS-SD RFC 6763) over Multicast DNS (mDNS RFC 6762),
  commonly known as and compatible with Apple Bonjour primarily targetting Linux.

  Copyright 2004-2015 by the Avahi developers.

confinement: strict
grade: stable

# expose services folder for other snaps
slots:
  services-content:
    interface: content
    write:
      - $SNAP_COMMON/etc/avahi/services
  daemon-socket:
    interface: content
    write:
      - $SNAP_COMMON/var/run/avahi-daemon

apps:
    avahi-daemon:
        command: avahi-daemon -f $SNAP_COMMON/etc/avahi/avahi-daemon.conf --no-drop-root --debug
        daemon: simple
        plugs:
          - network
          - network-bind
          - network-control
        slots:
          - avahi-observe
          - avahi-control

    restart-avahi-daemon:
        command: echo "run as root!" && avahi-daemon -r
        plugs:
          - network
          - network-bind
          - network-control
        slots:
          - avahi-observe
          - avahi-control

    help:
        command: avahi-help

parts:
    avahi:
        plugin: autotools
        source: .
        configflags:
          - --prefix=/usr
          - --disable-qt3
          - --disable-qt4
          - --disable-gtk
          - --disable-gtk3
          - --disable-gdbm
          - --disable-python
          - --disable-pygtk
          - --disable-python-dbus
          - --disable-mono
          - --disable-monodoc
          - --disable-manpages
          - --disable-xmltoman
          - --with-avahi-user=root
          - --with-avahi-group=root
          - --with-distro=debian
          - --disable-gobject
          - --sysconfdir=/var/snap/avahi/common/etc
          - --localstatedir=/var/snap/avahi/common/var
        build-packages: [gettext, intltool, libexpat1-dev, libdaemon-dev, libglib2.0-dev, xmltoman, libdbus-1-dev]
        stage-packages: [libdaemon0]
        prepare: |
            # disable chown call, as it won't pass security confinement
            sed -i 's#chown(#// chown(#g' avahi-daemon/main.c
        install: |
            # add tag with txt record os=snappy
            sed -i '/<\/service>/ i\    <txt-record>os=snappy</txt-record>' $SNAPCRAFT_PART_INSTALL/var/snap/avahi/common/etc/avahi/services/ssh.service
        organize:
          var/snap/avahi/common/etc: etc
          var/snap/avahi/common/var: var
        stage:
          - -var/snap

    hooks:
        source: snap-resources
        plugin: dump
        organize:
            avahi-help: bin/avahi-help
            config: bin/config
