#!/bin/bash

source $SNAP/bin/config &>/dev/null
echo -e "avahi snap help"

# parse config file for supported settings keys
echo -e "avahi supports settings keys"
echo -e "values can be changed by calling\n$ snap set avahi-ondra  <key name>='<key value>'"

echo -e "curretly defined keys"
for ((i=0;i<${#DEFINED_K[@]};++i)); do
    echo -e "\t${DEFINED_K[$i]}=${DEFINED_V[$i]}"
done

echo -e "keys with no set value:"
for ((i=0;i<${#UNDEFINED_K[@]};++i)); do
    echo -e "\t${UNDEFINED_K[i]#?}, proposed value '${UNDEFINED_V[i]}'"
done
